<a href="https://colab.research.google.com/github/somayeh-najafi/datasciense/blob/main/Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

In [2]:
uploaded = files.upload()

Saving df.csv to df.csv

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('df.csv')

In [5]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,$111K-$181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,$111K-$181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,$111K-$181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",$111K-$181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,$42K - $76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,$65 - $72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5892 entries, 0 to 5891
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5892 non-null   object
 1   Salary Estimate    5892 non-null   object
 2   Rating             5892 non-null   float64
 3   Company Name       5892 non-null   object
 4   Location           5892 non-null   object
 5   Size               5892 non-null   object
 6   Founded            5892 non-null   object
 7   Type of ownership  5892 non-null   object
 8   Industry           5892 non-null   object
 9   Sector             5892 non-null   object
 10  Revenue            5892 non-null   object
dtypes: float64(1), object(10)
memory usage: 506.5+ KB

In [8]:
df['Salary Estimate']

0       $111K-$181K (Glassdoor est.)
1       $111K-$181K (Glassdoor est.)
2       $111K-$181K (Glassdoor est.)
3       $111K-$181K (Glassdoor est.)
4       $111K-$181K (Glassdoor est.)
                    ...
5887    $42K - $76K (Glassdoor est.)
5888                              -1
5889                              -1
5890                              -1
5891              $65 - $72 Per Hour
Name: Salary Estimate, Length: 5892, dtype: object

In [6]:
def Dollar_remover(a):
  a = a.replace('$','')
  return(a)

In [9]:
df['Salary Estimate'].apply(Dollar_remover)

0       111K-181K (Glassdoor est.)
1       111K-181K (Glassdoor est.)
2       111K-181K (Glassdoor est.)
3       111K-181K (Glassdoor est.)
4       111K-181K (Glassdoor est.)
                   ...
5887    42K - 76K (Glassdoor est.)
5888                            -1
5889                            -1
5890                            -1
5891              65 - 72 Per Hour
Name: Salary Estimate, Length: 5892, dtype: object

In [7]:
df['Salary Estimate'] = df['Salary Estimate'].apply(Dollar_remover)

In [52]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111K-181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111K-181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111K-181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111K-181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111K-181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,42K - 76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [8]:
def K_remover(a):
  a = a.replace('K','')
  return(a)

In [53]:
df['Salary Estimate'].apply(K_remover)

0       111-181 (Glassdoor est.)
1       111-181 (Glassdoor est.)
2       111-181 (Glassdoor est.)
3       111-181 (Glassdoor est.)
4       111-181 (Glassdoor est.)
                  ...
5887    42 - 76 (Glassdoor est.)
5888                          -1
5889                          -1
5890                          -1
5891            65 - 72 Per Hour
Name: Salary Estimate, Length: 5892, dtype: object

In [9]:
df['Salary Estimate'] = df['Salary Estimate'].apply(K_remover)

In [55]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [10]:
df = df[df['Salary Estimate'] != '-1']

In [11]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5891,Data Scientist/ Full Stack Developer,65 - 72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [12]:
df = df[~df['Salary Estimate'].str.contains('Per Hour')]

In [14]:
df.to_csv('df1.csv')

In [32]:
text = 'I am somayeh'

In [34]:
text.split()[0]

'I'

In [15]:
df['Salary Estimate'].str.split()[0]

['111-181', '(Glassdoor', 'est.)']

In [37]:
df['Salary Estimate'].str.split()

0          [111-181, (Glassdoor, est.)]
1          [111-181, (Glassdoor, est.)]
2          [111-181, (Glassdoor, est.)]
3          [111-181, (Glassdoor, est.)]
4          [111-181, (Glassdoor, est.)]
                     ...
5881     [38, -, 64, (Glassdoor, est.)]
5882     [47, -, 89, (Glassdoor, est.)]
5883    [66, -, 113, (Glassdoor, est.)]
5886    [67, -, 111, (Glassdoor, est.)]
5887     [42, -, 76, (Glassdoor, est.)]
Name: Salary Estimate, Length: 5500, dtype: object

In [16]:
df['min_salary'] = None

In [39]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,None
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,None
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,None
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,None
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,None
...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 - 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),None
5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,None
5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,None
5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),None
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,None

In [17]:
df['max_salary'] = None

In [41]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,None,None
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,None,None
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,None,None
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,None,None
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 - 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),None,None
5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,None,None
5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,None,None
5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),None,None
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,None,None

In [18]:
df['average_salary'] = None

In [19]:
def min_salary(a):
  a = a.split()[0]
  return(a)

In [44]:
df['Salary Estimate'].apply(min_salary)

0       111-181
1       111-181
2       111-181
3       111-181
4       111-181
         ...
5881         38
5882         47
5883         66
5886         67
5887         42
Name: Salary Estimate, Length: 5500, dtype: object

In [20]:
def glass_remover(a):
  a =  a.split()[0]
  return(a)

In [47]:
df['Salary Estimate'] = df['Salary Estimate'].apply(glass_remover)

<ipython-input-47-63e0ea70448e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary Estimate'] = df['Salary Estimate'].apply(glass_remover)

In [2]:
df = pd.read_csv('df.csv')

NameError: name 'pd' is not defined

In [50]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,$111K-$181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,$111K-$181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,$111K-$181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",$111K-$181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,$42K - $76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,$65 - $72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [59]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,111-181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",111-181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,111-181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,111-181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",111-181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 - 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD)
5882,Supervisory Research Health Scientist,47 - 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5883,Senior SAS Programmer (Scientist),66 - 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5886,Senior Data Analyst - Product Analytics (open ...,67 - 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5887,Manufacturing Data Analyst Engineer,42 - 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable

In [21]:
def space_remover(a):
  a = a.replace(' - ','-')
  a = a.replace('-',' ')
  return(a)

In [22]:
df['Salary Estimate'] = df['Salary Estimate'].apply(space_remover)

In [23]:
df['Salary Estimate'].apply(min_salary)

0       111
1       111
2       111
3       111
4       111
       ...
5881     38
5882     47
5883     66
5886     67
5887     42
Name: Salary Estimate, Length: 5500, dtype: object

In [24]:
df['min_salary'] = df['Salary Estimate'].apply(min_salary)

In [68]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary
0,Senior Data Scientist,111 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111
1,"Data Scientist, Product Analytics",111 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111
2,Data Science Manager,111 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111
3,Data Analyst,111 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111
4,"Director, Data Science",111 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111
...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38
5882,Supervisory Research Health Scientist,47 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47
5883,Senior SAS Programmer (Scientist),66 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66
5886,Senior Data Analyst - Product Analytics (open ...,67 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67
5887,Manufacturing Data Analyst Engineer,42 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42

In [25]:
def max_salary(a):
  a = a.split()[1]
  return(a)

In [70]:
df['Salary Estimate'].apply(max_salary)

0       181
1       181
2       181
3       181
4       181
       ...
5881     64
5882     89
5883    113
5886    111
5887     76
Name: Salary Estimate, Length: 5500, dtype: object

In [26]:
df['max_salary'] = df['Salary Estimate'].apply(max_salary)

In [72]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary
0,Senior Data Scientist,111 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181
1,"Data Scientist, Product Analytics",111 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181
2,Data Science Manager,111 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181
3,Data Analyst,111 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181
4,"Director, Data Science",111 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64
5882,Supervisory Research Health Scientist,47 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89
5883,Senior SAS Programmer (Scientist),66 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113
5886,Senior Data Analyst - Product Analytics (open ...,67 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111
5887,Manufacturing Data Analyst Engineer,42 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76

In [73]:
df['average_salary'] = None

In [57]:
def average_salary(a,b):
  c = (a+b)/2
  return(c)

In [65]:
df['average_salary'] = average_salary(df['min_salary'],df['max_salary'])

In [64]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary
0,Senior Data Scientist,111 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,None
1,"Data Scientist, Product Analytics",111 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,None
2,Data Science Manager,111 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,None
3,Data Analyst,111 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,None
4,"Director, Data Science",111 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,None
5882,Supervisory Research Health Scientist,47 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,None
5883,Senior SAS Programmer (Scientist),66 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,None
5886,Senior Data Analyst - Product Analytics (open ...,67 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,None
5887,Manufacturing Data Analyst Engineer,42 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,None

In [29]:
def make_int(a):
  a = int(a)
  return(a)

In [34]:
df['min_salary'] = df['min_salary'].apply(make_int)

In [55]:
df['max_salary'].apply(make_int)

0       181
1       181
2       181
3       181
4       181
       ...
5881     64
5882     89
5883    113
5886    111
5887     76
Name: max_salary, Length: 5500, dtype: int64

In [36]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary
0,Senior Data Scientist,111 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,None
1,"Data Scientist, Product Analytics",111 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,None
2,Data Science Manager,111 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,None
3,Data Analyst,111 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,None
4,"Director, Data Science",111 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,None
5882,Supervisory Research Health Scientist,47 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,None
5883,Senior SAS Programmer (Scientist),66 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,None
5886,Senior Data Analyst - Product Analytics (open ...,67 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,None
5887,Manufacturing Data Analyst Engineer,42 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,None

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 5887
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5500 non-null   object
 1   Salary Estimate    5500 non-null   object
 2   Rating             5500 non-null   float64
 3   Company Name       5500 non-null   object
 4   Location           5500 non-null   object
 5   Size               5500 non-null   object
 6   Founded            5500 non-null   object
 7   Type of ownership  5500 non-null   object
 8   Industry           5500 non-null   object
 9   Sector             5500 non-null   object
 10  Revenue            5500 non-null   object
 11  min_salary         5500 non-null   int64
 12  max_salary         5500 non-null   object
 13  average_salary     0 non-null      object
dtypes: float64(1), int64(1), object(12)
memory usage: 773.6+ KB

In [51]:
df[df['max_salary'] == '250(Employer']

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary
2980,Diagnostic Research Scientist,200 250(Employer est.),3.9,Amazon\n3.9,"San Jose, CA",10000+ employees,1994,Company - Public,Internet,Information Technology,$10+ billion (USD),200,250(Employer,None
2981,Data Analyst,200 250(Employer est.),5.0,"Staffigo Technical Services, LLC\n5.0","San Jose, CA",51 to 200 employees,2008,Company - Private,IT Services,Information Technology,$50 to $100 million (USD),200,250(Employer,None
2982,Senior HR Data Analyst,200 250(Employer est.),4.6,NVIDIA\n4.6,"Santa Clara, CA",10000+ employees,1993,Company - Public,Computer Hardware & Software,Information Technology,$5 to $10 billion (USD),200,250(Employer,None
2983,"Machine Learning Engineer, TikTok Ads Integrity",200 250(Employer est.),3.8,TikTok\n3.8,"Mountain View, CA",1001 to 5000 employees,2016,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
2984,Data Analyst,200 250(Employer est.),4.1,IntelliPro Group Inc.\n4.1,"San Jose, CA",201 to 500 employees,-1,Company - Private,-1,-1,$10 to $25 million (USD),200,250(Employer,None
2985,Quantum Data Scientist (Industrial-Process sec...,200 250(Employer est.),3.7,IBM\n3.7,"San Jose, CA",10000+ employees,1911,Company - Public,IT Services,Information Technology,$10+ billion (USD),200,250(Employer,None
2986,Staff Data Engineer,200 250(Employer est.),3.4,Edelman Financial Engines\n3.4,"Santa Clara, CA",1001 to 5000 employees,1986,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,200,250(Employer,None
2987,Senior Data Scientist,200 250(Employer est.),3.9,PayPal\n3.9,"San Jose, CA",10000+ employees,1998,Company - Public,Internet,Information Technology,$10+ billion (USD),200,250(Employer,None
2988,"Marketing Data Scientist, gTech Professional S...",200 250(Employer est.),4.4,Google\n4.4,"Mountain View, CA",10000+ employees,1998,Company - Public,Internet,Information Technology,$10+ billion (USD),200,250(Employer,None
2989,"Data Scientist, Ad Platforms/Data Insights",200 250(Employer est.),4.1,Apple\n4.1,"Santa Clara, CA",10000+ employees,1976,Company - Public,Computer Hardware & Software,Information Technology,$10+ billion (USD),200,250(Employer,None
2990,Research Scientist,200 250(Employer est.),4.3,Carbon3D\n4.3,"Redwood City, CA",201 to 500 employees,2013,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
2991,Sr. Data Scientist - Platform Manipulation,200 250(Employer est.),4.0,Twitter\n4.0,"Sunnyvale, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$2 to $5 billion (USD),200,250(Employer,None
2992,"Data Scientist, Machine Learning",200 250(Employer est.),4.5,Facebook\n4.5,"Fremont, CA",10000+ employees,2004,Company - Public,Internet,Information Technology,$5 to $10 billion (USD),200,250(Employer,None
2993,Data Science Developer,200 250(Employer est.),3.6,Signature Consultants\n3.6,"Redwood City, CA",1001 to 5000 employees,1997,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD),200,250(Employer,None
2994,Data Scientist Machine Learning at Google,200 250(Employer est.),4.2,Scopus IT\n4.2,"Redwood City, CA",1 to 50 employees,2007,Company - Private,Enterprise Software & Network Solutions,Information Technology,Less than $1 million (USD),200,250(Employer,None
2995,NLP Data Scientist,200 250(Employer est.),4.5,Aisera\n4.5,"Palo Alto, CA",51 to 200 employees,2017,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
2996,"AI/ML - Machine Learning Engineer, Advanced De...",200 250(Employer est.),4.1,Apple\n4.1,"Santa Clara, CA",10000+ employees,1976,Company - Public,Computer Hardware & Software,Information Technology,$10+ billion (USD),200,250(Employer,None
2997,Staff Software Engineer - Data Platform,200 250(Employer est.),4.5,Strivr\n4.5,"Palo Alto, CA",51 to 200 employees,2015,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
2998,Data science researcher,200 250(Employer est.),3.9,PayPal\n3.9,"San Jose, CA",10000+ employees,1998,Company - Public,Internet,Information Technology,$10+ billion (USD),200,250(Employer,None
2999,"Community Data Manager, Single-Cell Biology",200 250(Employer est.),3.4,Chan Zuckerberg Initiative\n3.4,"Redwood City, CA",201 to 500 employees,2015,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
3000,Principal Data Scientist-Recommendation Systems,200 250(Employer est.),3.6,Appen\n3.6,"Sunnyvale, CA",1001 to 5000 employees,1996,Company - Public,Consulting,Business Services,$50 to $100 million (USD),200,250(Employer,None
3001,"Senior/Staff Software Engineer, Data Infrastru...",200 250(Employer est.),3.1,Earnin\n3.1,"Palo Alto, CA",201 to 500 employees,2012,Company - Private,IT Services,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
3002,Data Scientist Technical Lead,200 250(Employer est.),4.4,Google\n4.4,"Mountain View, CA",10000+ employees,1998,Company - Public,Internet,Information Technology,$10+ billion (USD),200,250(Employer,None
3003,"Data Scientist, Gateway Analytics (Novi)",200 250(Employer est.),4.5,Facebook\n4.5,"Menlo Park, CA",10000+ employees,2004,Company - Public,Internet,Information Technology,$5 to $10 billion (USD),200,250(Employer,None
3004,Sr. Data Scientist/Analyst,200 250(Employer est.),4.1,Apple\n4.1,"Santa Clara, CA",10000+ employees,1976,Company - Public,Computer Hardware & Software,Information Technology,$10+ billion (USD),200,250(Employer,None
3005,Data Analyst,200 250(Employer est.),3.9,Accounting Principals\n3.9,"San Jose, CA",501 to 1000 employees,1994,Company - Public,Staffing & Outsourcing,Business Services,$10 to $25 million (USD),200,250(Employer,None
3006,"Senior Data Scientist, Machine Learning",200 250(Employer est.),4.4,Atlassian\n4.4,"Mountain View, CA",1001 to 5000 employees,2002,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,200,250(Employer,None
3007,"Data Scientist, Engineering",200 250(Employer est.),4.4,Google\n4.4,"Mountain View, CA",10000+ employees,1998,Company - Public,Internet,Information Technology,$10+ billion (USD),200,250(Employer,None
3008,Senior Data Analyst,200 250(Employer est.),3.1,Bandai Namco Entertainment America\n3.1,"Santa Clara, CA",51 to 200 employees,1990,Subsidiary or Business Segment,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),200,250(Employer,None

In [47]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary
0,Senior Data Scientist,111 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,None
1,"Data Scientist, Product Analytics",111 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,None
2,Data Science Manager,111 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,None
3,Data Analyst,111 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,None
4,"Director, Data Science",111 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,None
5882,Supervisory Research Health Scientist,47 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,None
5883,Senior SAS Programmer (Scientist),66 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,None
5886,Senior Data Analyst - Product Analytics (open ...,67 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,None
5887,Manufacturing Data Analyst Engineer,42 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,None

In [52]:
def max_salary_space(a):
  a = a.replace('(E',' (E)')
  a = a.split()[0]
  return(a)

In [53]:
df['max_salary'].apply(max_salary_space)

0       181
1       181
2       181
3       181
4       181
       ...
5881     64
5882     89
5883    113
5886    111
5887     76
Name: max_salary, Length: 5500, dtype: object

In [54]:
df['max_salary'] = df['max_salary'].apply(max_salary_space)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 5887
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5500 non-null   object
 1   Salary Estimate    5500 non-null   object
 2   Rating             5500 non-null   float64
 3   Company Name       5500 non-null   object
 4   Location           5500 non-null   object
 5   Size               5500 non-null   object
 6   Founded            5500 non-null   object
 7   Type of ownership  5500 non-null   object
 8   Industry           5500 non-null   object
 9   Sector             5500 non-null   object
 10  Revenue            5500 non-null   object
 11  min_salary         5500 non-null   int64
 12  max_salary         5500 non-null   int64
 13  average_salary     0 non-null      object
dtypes: float64(1), int64(2), object(11)
memory usage: 773.6+ KB

In [61]:
df['max_salary'] = df['max_salary'].apply(make_int)

In [66]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary
0,Senior Data Scientist,111 181 (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0
1,"Data Scientist, Product Analytics",111 181 (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0
2,Data Science Manager,111 181 (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0
3,Data Analyst,111 181 (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0
4,"Director, Data Science",111 181 (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,38 64 (Glassdoor est.),3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0
5882,Supervisory Research Health Scientist,47 89 (Glassdoor est.),4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0
5883,Senior SAS Programmer (Scientist),66 113 (Glassdoor est.),4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5
5886,Senior Data Analyst - Product Analytics (open ...,67 111 (Glassdoor est.),4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0
5887,Manufacturing Data Analyst Engineer,42 76 (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 5887
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5500 non-null   object
 1   Salary Estimate    5500 non-null   object
 2   Rating             5500 non-null   float64
 3   Company Name       5500 non-null   object
 4   Location           5500 non-null   object
 5   Size               5500 non-null   object
 6   Founded            5500 non-null   object
 7   Type of ownership  5500 non-null   object
 8   Industry           5500 non-null   object
 9   Sector             5500 non-null   object
 10  Revenue            5500 non-null   object
 11  min_salary         5500 non-null   int64
 12  max_salary         5500 non-null   int64
 13  average_salary     5500 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 773.6+ KB