<a href="https://colab.research.google.com/github/somayeh-najafi/datasciense/blob/main/Week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
from google.colab import files

In [26]:
uploaded = files.upload()

Saving df.csv to df (2).csv

In [22]:
import pandas as pd

In [27]:
df = pd.read_csv('df.csv')

In [28]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,$111K-$181K (Glassdoor est.),3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics",$111K-$181K (Glassdoor est.),4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,$111K-$181K (Glassdoor est.),-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,$111K-$181K (Glassdoor est.),3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science",$111K-$181K (Glassdoor est.),3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5887,Manufacturing Data Analyst Engineer,$42K - $76K (Glassdoor est.),3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable
5888,Data Scientist,-1,4.9,Bluetree Network\n4.9,"Madison, WI",-1,-1,-1,-1,-1,-1
5889,Supply Chain Consultant - Data Scientist,-1,4.0,"Kimberly-Clark Corporation, LLC\n4.0","Neenah, WI",10000+ Employees,1872,Company - Public,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD)
5890,Data Science Engineer,-1,4.0,AE Business Solutions\n4.0,"Madison, WI",51 to 200 Employees,1949,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD)
5891,Data Scientist/ Full Stack Developer,$65 - $72 Per Hour,3.7,Epitec\n3.7,"Wisconsin, WI",1001 to 5000 Employees,1978,Company - Private,Staffing & Outsourcing,Business Services,$100 to $500 million (USD)

In [29]:
def dollar_K_remover(a):
  a = a.replace('$','')
  a = a.replace('K','')
  return(a)

In [31]:
df['Salary Estimate'] = df['Salary Estimate'].apply(dollar_K_remover)

In [34]:
df = df[~df['Salary Estimate'].str.contains('Per Hour')]

In [43]:
df = df[df['Salary Estimate'] != '-1']

In [45]:
def space_fix(a):
  a = a.replace('-',' - ')
  return(a)

In [46]:
df['Salary Estimate'].apply(space_fix)

0        111 - 181 (Glassdoor est.)
1        111 - 181 (Glassdoor est.)
2        111 - 181 (Glassdoor est.)
3        111 - 181 (Glassdoor est.)
4        111 - 181 (Glassdoor est.)
                   ...
5881     38  -  64 (Glassdoor est.)
5882     47  -  89 (Glassdoor est.)
5883    66  -  113 (Glassdoor est.)
5886    67  -  111 (Glassdoor est.)
5887     42  -  76 (Glassdoor est.)
Name: Salary Estimate, Length: 5500, dtype: object

In [48]:
df_new = df

In [49]:
df['Salary Estimate'] = df['Salary Estimate'].apply(space_fix)

<ipython-input-49-dec4dd28df6d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary Estimate'] = df['Salary Estimate'].apply(space_fix)

In [37]:
def splitter(a):
  a = a.split()
  return (a)

In [53]:
df['Salary Estimate'] = df['Salary Estimate'].apply(splitter)

<ipython-input-53-307f68321d09>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary Estimate'] = df['Salary Estimate'].apply(splitter)

In [51]:
df['Salary Estimate'][0].split()

['111', '-', '181', '(Glassdoor', 'est.)']

In [54]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable
1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable
2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable
3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable
4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable
...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD)
5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable
5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable
5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD)
5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable

In [57]:
def min_finder(a):
  a = a[0]
  return(a)

In [58]:
df['min_salary'] = df['Salary Estimate'].apply(min_finder)

<ipython-input-58-48e7a9e43310>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['min_salary'] = df['Salary Estimate'].apply(min_finder)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 5887
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5500 non-null   object
 1   Salary Estimate    5500 non-null   object
 2   Rating             5500 non-null   float64
 3   Company Name       5500 non-null   object
 4   Location           5500 non-null   object
 5   Size               5500 non-null   object
 6   Founded            5500 non-null   object
 7   Type of ownership  5500 non-null   object
 8   Industry           5500 non-null   object
 9   Sector             5500 non-null   object
 10  Revenue            5500 non-null   object
 11  min_salary         5500 non-null   object
dtypes: float64(1), object(11)
memory usage: 687.6+ KB

In [60]:
def max_finder(a):
  a = a[2]
  return(a)

In [61]:
df['max_salary'] = df['Salary Estimate'].apply(max_finder)

<ipython-input-61-590b38b11990>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_salary'] = df['Salary Estimate'].apply(max_finder)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 5887
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5500 non-null   object
 1   Salary Estimate    5500 non-null   object
 2   Rating             5500 non-null   float64
 3   Company Name       5500 non-null   object
 4   Location           5500 non-null   object
 5   Size               5500 non-null   object
 6   Founded            5500 non-null   object
 7   Type of ownership  5500 non-null   object
 8   Industry           5500 non-null   object
 9   Sector             5500 non-null   object
 10  Revenue            5500 non-null   object
 11  min_salary         5500 non-null   int64
 12  max_salary         5500 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 730.6+ KB

In [64]:
df['min_salary'] = df['min_salary'].astype('int')

<ipython-input-64-df6c365c8ccc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['min_salary'] = df['min_salary'].astype('int')

In [77]:
df['max_salary'] = df['max_salary'].astype('int')

<ipython-input-77-ea3673775c0f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_salary'] = df['max_salary'].astype('int')

In [76]:
df[df['max_salary'] == '250(Employer']

Empty DataFrame
Columns: [Job Title, Salary Estimate, Rating, Company Name, Location, Size, Founded, Type of ownership, Industry, Sector, Revenue, min_salary, max_salary]
Index: []

In [72]:
def employer_fix(a):
  a = a.replace('(Employer',' (Employer')
  a = a.split()[0]
  return(a)

In [75]:
df['max_salary'] = df['max_salary'].apply(employer_fix)

<ipython-input-75-1bd307ab1899>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['max_salary'] = df['max_salary'].apply(employer_fix)

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5500 entries, 0 to 5887
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          5500 non-null   object
 1   Salary Estimate    5500 non-null   object
 2   Rating             5500 non-null   float64
 3   Company Name       5500 non-null   object
 4   Location           5500 non-null   object
 5   Size               5500 non-null   object
 6   Founded            5500 non-null   object
 7   Type of ownership  5500 non-null   object
 8   Industry           5500 non-null   object
 9   Sector             5500 non-null   object
 10  Revenue            5500 non-null   object
 11  min_salary         5500 non-null   int64
 12  max_salary         5500 non-null   int64
 13  average_salary     5500 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 773.6+ KB

In [79]:
df['average_salary'] = (df['min_salary']+df['max_salary'])/2

<ipython-input-79-8f7547a8ae96>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['average_salary'] = (df['min_salary']+df['max_salary'])/2

In [81]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary
0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0
1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0
2,Data Science Manager,"[111, -, 181, (Glassdoor, est.)]",-1.0,Decode_M,"New York, NY",1 to 50 employees,-1,Unknown,-1,-1,Unknown / Non-Applicable,111,181,146.0
3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0
4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0
5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0
5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5
5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0
5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0

In [83]:
df = df[df['Rating'] != -1]

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4895 entries, 0 to 5887
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          4895 non-null   object
 1   Salary Estimate    4895 non-null   object
 2   Rating             4895 non-null   float64
 3   Company Name       4895 non-null   object
 4   Location           4895 non-null   object
 5   Size               4895 non-null   object
 6   Founded            4895 non-null   object
 7   Type of ownership  4895 non-null   object
 8   Industry           4895 non-null   object
 9   Sector             4895 non-null   object
 10  Revenue            4895 non-null   object
 11  min_salary         4895 non-null   int64
 12  max_salary         4895 non-null   int64
 13  average_salary     4895 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 573.6+ KB

In [85]:
df['Location'].value_counts()

Austin, TX         310
Chicago, IL        306
San Diego, CA      282
New York, NY       262
Columbus, OH       201
                  ...
Pensacola, FL        1
Seminole, FL         1
Orange City, FL      1
Tamarac, FL          1
Euclid, OH           1
Name: Location, Length: 466, dtype: int64

In [86]:
def state_finder(a):
  a = a.split()[-1]
  return(a)

In [87]:
df['state'] = df['Location'].apply(state_finder)

<ipython-input-87-a48459728284>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['state'] = df['Location'].apply(state_finder)

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4895 entries, 0 to 5887
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          4895 non-null   object
 1   Salary Estimate    4895 non-null   object
 2   Rating             4895 non-null   float64
 3   Company Name       4895 non-null   object
 4   Location           4895 non-null   object
 5   Size               4895 non-null   object
 6   Founded            4895 non-null   object
 7   Type of ownership  4895 non-null   object
 8   Industry           4895 non-null   object
 9   Sector             4895 non-null   object
 10  Revenue            4895 non-null   object
 11  min_salary         4895 non-null   int64
 12  max_salary         4895 non-null   int64
 13  average_salary     4895 non-null   float64
 14  state              4895 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 611.9+ KB

In [89]:
df['state']

0       NY
1       NY
3       NJ
4       NY
5       NY
        ..
5881    OH
5882    OH
5883    OH
5886    OH
5887    OH
Name: state, Length: 4895, dtype: object

In [93]:
df['state'].value_counts()

CA    1154
TX    1102
OH     380
IL     340
PA     303
NY     270
AZ     262
FL     227
MA     207
NJ     204
MI     181
VA     114
DC      72
MD      56
DE       9
WI       3
GA       1
ME       1
KY       1
NM       1
NH       1
IN       1
NC       1
Name: state, dtype: int64

In [92]:
df = df[df['state'] != 'Kingdom']

In [94]:
df

,Job Title,Salary Estimate,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,min_salary,max_salary,average_salary,state
0,Senior Data Scientist,"[111, -, 181, (Glassdoor, est.)]",3.5,Hopper\n3.5,"New York, NY",501 to 1000 employees,2007,Company - Private,Travel Agencies,Travel & Tourism,Unknown / Non-Applicable,111,181,146.0,NY
1,"Data Scientist, Product Analytics","[111, -, 181, (Glassdoor, est.)]",4.5,Noom US\n4.5,"New York, NY",1001 to 5000 employees,2008,Company - Private,"Health, Beauty, & Fitness",Consumer Services,Unknown / Non-Applicable,111,181,146.0,NY
3,Data Analyst,"[111, -, 181, (Glassdoor, est.)]",3.4,Sapphire Digital\n3.4,"Lyndhurst, NJ",201 to 500 employees,2019,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,111,181,146.0,NJ
4,"Director, Data Science","[111, -, 181, (Glassdoor, est.)]",3.4,United Entertainment Group\n3.4,"New York, NY",51 to 200 employees,2007,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,111,181,146.0,NY
5,Data Scientist,"[111, -, 181, (Glassdoor, est.)]",2.9,IFG Companies\n2.9,"New York, NY",201 to 500 employees,1985,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,111,181,146.0,NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5881,Information Scientist,"[38, -, 64, (Glassdoor, est.)]",3.2,CAS\n3.2,"Columbus, OH",1001 to 5000 Employees,1907,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),38,64,51.0,OH
5882,Supervisory Research Health Scientist,"[47, -, 89, (Glassdoor, est.)]",4.2,Centers for Disease Control and Prevention\n4.2,"Cincinnati, OH",10000+ Employees,1946,Government,Federal Agencies,Government,Unknown / Non-Applicable,47,89,68.0,OH
5883,Senior SAS Programmer (Scientist),"[66, -, 113, (Glassdoor, est.)]",4.0,Certara\n4.0,"Cincinnati, OH",501 to 1000 Employees,2008,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,66,113,89.5,OH
5886,Senior Data Analyst - Product Analytics (open ...,"[67, -, 111, (Glassdoor, est.)]",4.0,New Relic\n4.0,"Cincinnati, OH",1001 to 5000 Employees,2008,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),67,111,89.0,OH
5887,Manufacturing Data Analyst Engineer,"[42, -, 76, (Glassdoor, est.)]",3.6,Hose Master\n3.6,"Euclid, OH",201 to 500 Employees,1982,Company - Private,Electrical & Electronic Manufacturing,Manufacturing,Unknown / Non-Applicable,42,76,59.0,OH

In [95]:
df['Job Title'].value_counts()

Data Scientist                                                   530
Data Analyst                                                     296
Data Engineer                                                    267
Senior Data Scientist                                            117
Machine Learning Engineer                                         55
                                                                ...
Data Scientist - Top Secret w/ SCI Eligibility                     1
Business Intelligence Analyst I                                    1
Business Intelligence Analyst Senior (Chief Financial Office)      1
Business Intelligence Analyst III - Credit Card                    1
Manufacturing Data Analyst Engineer                                1
Name: Job Title, Length: 2552, dtype: int64

In [96]:
set(df['Job Title'])

{'Senior Scientist - CMC Analytical Development',
 'LEAD COMPUTER SCIENTIST - SR. COMPUTER SCIENTIST - SPACE DATA SYSTEMS',
 'Epidemiologist - Data Analyst',
 'Soil Scientist (Direct Hire)',
 'Associate Food Scientist - Global Expansion Team',
 'Senior Consulting Data Analyst',
 'Sr. Data Analyst - Growth & Adoption',
 'Molecular Engineering Senior Research Scientist',
 'Pipeline Integrity - Data Scientist',
 'Scientist Data Analytics',
 'ETL/Data Engineer I (datastage)',
 'Data Scientist *',
 'Data Architect',
 'COMPUTER SCIENTIST - ENGINEER - RESEARCH ENGINEER - PERFORMANCE METROLOGY',
 'Research Scientist - Reactive Materials',
 'Data Analyst, Data & Analytics (Advanced Analytics) Manager (Multiple Positions)',
 'Data Analyst - 310001',
 'CLINICAL LABORATORY SCIENTIST I',
 'Quantitative Researcher',
 'Quantitative Analyst Intern',
 'Quantitative Analyst',
 'Data Engineer II - ETL Engineer - Spectrum Enterprise',
 'Data Scientist Principal',
 'Senior Data Scientist, FP&A',
 'Data Analyst - IntelliScript',
 'Entry Level Data Scientist',
 'Part-Time Instructor (Data Science)',
 'Consultant, Analytic Scientist (Model Steward)',
 'Research Area Specialist Senior - Data Analyst (Term-Limited)',
 'Cloud Data Solution Architect',
 'Sr. Data Science Architect',
 'Senior Data Scientist - Defense & Intelligence',
 'Senior Data Engineer with Kafka-Yarn-Spark-HDFS and HIVE',
 'Machine Learning Engineer',
 'Scientist, Bioanalytics, Gene Therapy',
 'Data Engineer AWS, ETL, Python - San Diego, CA (remote for now',
 'MS Data Scientist',
 'Research Scientist - Radar',
 'VBA Software developer / IT Data Analyst SQL',
 'Senior Data & Engineering Lead',
 'Hadoop Developer / Data Engineer / Bigdata Engineer / Big Data Engineer',
 'Quantitative Researcher – Full Time (US)',
 'Research Scientist - Neural Interfaces',
 'Data Analyst Lead - SAP',
 'Principal Data Engineering Architect - Data Pipelines',
 'Sr. Analytics Consultant',
 'Attending Veterinarian / Principal Scientist',
 'Machine Learning Engineer, Planner/Behavior Prediction',
 'Sr Data Scientist - Strategic Risk – Lead',
 'Data Scientist - Medical Device',
 'Advanced Analytics Consultant',
 'Data Modeler (Data Vault)',
 'Data Analyst, Center on Immigration and Justice (CIJ)',
 'Azure Data Engineer',
 'Senior Big Data Engineer - QuantumBlack',
 'Behavorial Health Data Analyst',
 'Senior Cloud Data Analyst',
 'Global Risk Review Banking Book Data Analyst',
 'Machine Learning Engineer (OH)',
 'Medical Lab Scientist Specialist - Microbiology',
 'Scientist I, Manufacturing Sciences - West Hills',
 'Data Scientist (M&I)',
 'Staff Software Scientist, Reproductive Health',
 '(Data Analyst) BA/BSA',
 'Senior Strategy & Data Analyst',
 'Data Visualization Engineer',
 'Remote Senior Data Scientist (Healthcare / Claims Data)',
 'Data Manager (Software Engineer II)',
 'In Vivo Principal Scientist',
 'Senior Data Scientist - Ads Optimization',
 'Applied Scientist, Machine Learning (BK or SF)',
 'Only W2-Data Engineer(Bigdata, AWS, Lambda,Python, Spark)',
 'Research Scientist - Data Science (Earth & Atmospheric Sciences)',
 'Automatic Benchmark Research Scientist - San Diego',
 'Research Scientist - Biopharm cGMP Reports, and Regulatory Documentation',
 'Regional Medical Scientist (RMS) - South Region (TX, OK, AR, LA)',
 'Senior Data Science Engineer',
 'Data Scientist - Advanced Analytics',
 'Analyst II/Assistant Director, Data Science',
 'Data Scientist/AI Scientist',
 'Scientist',
 'Architect, Data Intelligence',
 'Food Scientist',
 'Data Scientist for Alpha Insights',
 'Application Vulnerability Governance Lead Data Analyst',
 'Research Scientist 1 (General Toxicology) 1 1',
 'Business Intelligence Analyst II - Finance - Revenue Cycle Support Systems',
 'Sr Big Data Engineer',
 'Senior SAS Data Engineer',
 'Data Analytics/ Data scientist',
 'Project Scientist II',
 '(Data Risk Analyst: Data Modeler)',
 'Senior Associate Scientist, Biophysical Screening',
 'LEAD ENGINEER - SR. COMPUTER SCIENTIST - SR. RESEARCH ENGINEER - UNMANNED SYSTEMS',
 'Data Analyst',
 'Senior SW Engineer, Data Science ( Kubernetes/ Docker ) - Remote USA',
 'Digital Data & Identity Analyst',
 'Data Scientist 2 (Tableau Statistics (IT Portfolio), Predictive Analysis & Visualization)',
 'ETL QA / Data Analyst',
 'Data Scientist, Cell Quality & Field Reliability',
 'Omnichannel Marketing Data Analyst',
 'Data Scientist II, Data, Models & Decisions',
 'Senior HR Data Analyst',
 'Senior Claims Data Analyst',
 'Data Analyst, Budget & Management, Security Customer Success',
 'Data Science Sr. Analyst',
 'Data Modeler Consultant',
 'Data Analyst & Healthcare Analytics',
 'Senior Data Scientist -Business Analytics',
 'Principal Data Scientist, Bioinformatics',
 'Sr Data Scientist - PHI',
 'X-Ray Research Scientist',
 'Sr. Data Scientist/Data Engineer, AI (Tech Delivery Lead) – New York, NY/Dallas, TX',
 'Nurse Scientist - Nursing Research',
 'Data Scientist / Sports Scientist',
 'AI/ML Research Scientist',
 'Environmental Compliance Scientist',
 'Research Scientist-Medicinal Chemistry',
 'Compensation & HR Data Analyst',
 'Finance & Healthcare Analytics Manager',
 'Process Development Scientist |PR',
 'ML Platform - Data Analyst',
 'Tenured/Tenure-Track Professor, Department of Statistics & Data Sciences',
 'Development Scientist I/II, Amplification',
 'Field Appl Scientist I',
 'ICM Quantitative Analytics Senior - Data Science',
 'Business Intelligence - Data Analyst',
 'Austin Data Science Tutor Jobs',
 'Procurement Data Analyst',
 'Data Scientist - Forecasting',
 'Scientist, Product Development',
 'Sr Applied Scientist',
 'Data Engineer and Visualization Developer',
 'Financial Data Analyst (North of Chicago)',
 'Basel Data Analyst',
 'Senior Scientist',
 'MS&T Scientist I',
 'Analyst - Data Analyst Reporting',
 'Senior Healthcare Data Analyst - Multiple Positions',
 'Analytical Consultant #2020',
 'ES194 Earth Science Data Support',
 'Staff Machine Learning Engineer - HBO Max',
 'Senior Data Analyst - Global Product Group',
 'Video Codec Scientist',
 'Associate Scientist: Microbiology',
 'Data Analyst (Product Analytics)',
 'Data Engineer, DevOps - Remote OK',
 'Scientist I/II Upstream/Downstream PD [JC-1463]',
 'Systems Engineer - Data Engineer',
 'Medical Laboratory Scientist - Core Lab - Part-Time',
 'JPSC-6455 - Big Data Engineer with HL7 Healthcare/Python',
 'Data Scientist, Power & Performance',
 'Director of Health Data Science',
 'Applied Cybersecurity Reseach Scientist, Advance Cyber Science',
 'Principal Data Scientist- Public Sector',
 'Data Modeler, JLL Technologies',
 'Scientist IV, Formulation Pharmaceutics',
 'Data Scientist, Finance',
 'Scientist / Associate Scientist, Cancer Immunotherapy',
 'Technical Service Scientist',
 'Senior Data Analyst, People Analytics',
 'Pharmaceutical Upstream Processing Scientist - III',
 'Data Analyst, Public Health Laboratory',
 'Azure Data Engineer- Houston TX',
 'Senior Scientist, Scientific Affairs',
 'Senior Data Modeler',
 'Data Analyst - Rush Infectious Diseases',
 'Financial and Data Analyst',
 'Data analyst',
 'Senior Scientist (Molecular Dx Dermatology',
 'Full Stack Data Scientist Intern - Fall 2020 / Spring',
 'Principal,Software/ Data Engineer',
 'Data Engineer, Senior',
 'Senior Data Scientist - Opportunity for Working Remotely Boston, MA',
 'Data Consultant, Direct Marketing Campaign Automation',
 'Chief Architect - Systems and Data Management Software',
 'Software Engineer - Data Engineering, Finance Products',
 'Scientist - Autonomous Robotics in Manufacturing',
 'Associate Engineer/Scientist',
 'Data Specialist',
 'AI Insights Data Analyst',
 'Staff Data Custodian - Onshore',
 'Sr Associate Scientist, Phage Display, Molecular Biology',
 'Image Scientist',
 'Associate Scientist - Immunology - Project Scientist',
 'Digital SW Eng Lead/Data Engineer',
 'Product Development Scientist - Cell Analysis',
 'Director Data Scientist - Data Science Hub',
 'IT Data Engineer with Data Catalog',
 'COMPUTER SCIENTIST - ENGINEER - RESEARCH COMPUTER SCIENTIST - ADVANCED INSPECTION SYSTEMS',
 'Scientist III, QC Aero Star 2nd Shift',
 'LEAD DATA SCIENTIST',
 'Optimization Engineer- Data Scientist- Columbus, OH Plant',
 'Principal/Senior Data Scientist',
 'Senior Research Scientist, Neurotechnology',
 'Field Application Scientist',
 'Quantitative Research Associate',
 'Scientist I / Scientist II, Computational Biology',
 'Principal Scientist, Analytical Chemistry',
 'VP of Data Science & Analytics',
 'Medical Lab Scientist (MLS)- Evening Shift',
 'Data Engineer/Scientist',
 'Lead Data Scientist – Secret Clearance Required',
 'Senior Scientist, Bioanalytical Study Management',
 'Data Analytics Architect',
 'Data Science Program Coordinator',
 'machine learning Engineer with AWS',
 'Mid-Level Data Engineer',
 'Azure Data Engineer@Houston, TX',
 'Senior Data & Applied Scientist',
 'Electronics Engineer/Computer Scientist',
 'Manager of Data Science',
 'Research Scientist Sr- RI Deans',
 'Senior Data Engineer - Information Security',
 'Data Engineer (Enterprise Content Management with FileNet)',
 'Data Science Engineer',
 'Data Engineer - Orion',
 'Senior Data Analyst (002.082)',
 'Data Analyst - Sales Quality',
 'Technical Associate I/Data Scientist, Fraenkel Lab',
 'Data Scientist - Data Analytics',
 'Senior Scientist-UV Coatings',
 'Data Scientist - Trust & Safety, Law Enforcement',
 'AI - Natural Language Processing and Machine Learning Engineer',
 'Geologist or Environmental Scientist - Entry Level',
 'Principal Scientist, Chemical Development',
 'Siri - Machine Learning Engineer, Speech and Audio Systems',
 'Data Scientists',
 'Data Sceintist',
 'Natural Catastrophe Research Scientist',
 'Machine learning engineer',
 'Manager, Data Science, Risk',
 'Data Science & Machine Learning',
 'Scientist/Associate Scientist, Process Development',
 'Quantitative Analyst – Model Validation',
 'Senior Data Scientist - R&D Oncology',
 'Sr. Computational Biologist, Oncology Drug Discovery',
 'Quantitative Research Developer',
 'Principal Data Scientist - R&D Oncology',
 'Scientist - Comparative Medicine',
 'Staff Data Engineer (Oracle ERP/HCM)',
 'Sr Professional, Data Engineer',
 'Contract Data Analyst',
 'Data Analyst – Energy Conservation Measure (ECM) Program',
 'Scientist I/II',
 'Point72 Healthcare Data Scientist',
 'Data Scientist, Personalization',
 'Financial Quantitative Analyst, Financial Services Risk Management - Structured Finance - Financial Services Office (Senior) (Multiple Positions)',
 'DBA / Data Analyst',
 'Lead Data Scientist, People Analytics and Insights',
 'Data Science – Analyst/Associate - Security Incident Response Team',
 'Product Management Data Scientist',
 'Associate, Rotational Development– Data Science Track Corp Strategy',
 'Data Scientist, Portfolio & Data Insights',
 'Senior Data Science Consultant',
 'Quantum Principal Data Scientist (Industrial-Discrete sector)',
 'Scientist III (Molecular Biology)',
 'Data Scientist/Modeler',
 'Ergonomics Scientist',
 'Clinical Scientist, Vaccines',
 'Manager, Data Science - Native Shopping Analytics',
 'Epidemiologist/Data Scientist',
 'Senior. Data Engineer - Informatica',
 'Senior Strategy Data Analyst',
 'Consultant Data Scientist – Healthcare H/F',
 'Global Reporting and Analytics Consultant',
 'Data Operations Engineer',
 'Data Analyst-(analytics)',
 'IRIS Data Analyst',
 'Data Scientist/ Full Stack Developer',
 'Data Scientist 3 (Tableau - Statistics (Fleet Readiness), Tableau - Statistics (IT Portfolio), Predi',
 'Quantitative Analyst - Asset Allocation Analyst',
 'SAS Data Engineer',
 'Deep Learning Research Scientist / Engineer (Deep Learning & Algorithms)',
 'Real-World Analytics & Data Science (RADS) Fellowship',
 'Data Scientist, Small Business Group',
 'Data Scientist I Seller Development',
 'Data Science Software Engineer',
 '#104733 HPC Systems and Data Engineer',
 'Master Data Analyst I',
 'Sr. Data Scientist, Database Marketing',
 '20-63 Flood Planning Data Analyst (Data Analyst III)',
 'Quantitative Research Scientist',
 'Analytical Consultant',
 'Software Engineer, Data Warehousing',
 'Research Scientist III',
 'Scientist, In Vivo Pharmacology',
 'Director, Network Optimization & Data Sciences',
 'Analytical Scientist I',
 'Food Scientist - Foodservice',
 'Future Position: Data Scientist',
 'Pharmaceutical Customer Data Analyst',
 'DCW-Data Science Lead for DCW-FLL/TPA-C14',
 'Quantitative Researcher – PhD Hire',
 'Artificial Intelligence Research Scientist',
 'Ad Integrity Data Analyst-ATX',
 'TECAN Automation Scientist',
 'Associate Director, IT Business Partnering, Genomic Data & Technologies',
 'In Vivo Senior Principal Scientist',
 'Sr. BI Data Engineer III',
 'Senior Scientist, Developability',
 'Senior Applied Machine Learning Engineer',
 'Process Development Scientist',
 'Senior Data Scientist, Advanced Analytics / AI CoE',
 'Pricing Data Analyst',
 'Master Data Analyst',
 'Manager Data Scientist, Analytics & Insights',
 'Big Data Engineer/Architect',
 'Data Scientist - Researcher',
 'Adjunct Faculty - Advanced Quantitative Research Design and Analysis',
 'IT Data Analyst',
 'Sr Analyst, Data Scientist Business Intelligence (1 of 2 Openings)',
 'Data Scientist, Engineering',
 'Data Scientist - Product Analytics',
 'Quantitative Researcher – Intern',
 'Clinical Laboratory Scientist Data Review',
 'Staff Scientist',
 'CIB - Data Scientist',
 'Sr. Applied Scientist',
 'Post Doctoral Scientist - RI Biobehavioral Taylor',
 'Scientist 2, Data Analytics',
 'Sr. Data Analyst - Guidewire Data Hub',
 'Data Scientist II',
 'Research Scientist - IMM',
 'Data Science Lead',
 'Global Big Data Scientist',
 'CLINICAL DATA ANALYST',
 'Data Analyst Junior',
 'BI Data Analyst - Predictive Analytics',
 'Automotive eCommerce Data Analyst',
 'Payment Integrity Data Analyst',
 'Bioinfo-Comput Biologist Assoc',
 'Data Scientist - Risk',
 'Data Engineer - IG Tech',
 'Senior Scientist, Biology',
 'Systems Support-Data Analyst',
 'Health Data Analyst',
 'Senior Big Data Analyst',
 'Data Scientist Consultant',
 'Sr Quantitative Analyst',
 'Senior Scientist, Decision Sciences',
 'Associate, Rotational Development– Data Science Track BI &A',
 'Data Analyst D',
 'Senior Scientist - Medical Device',
 'Manufacturing Science and Technology (MS&T) Scientist',
 'Data Engineer, Ad Technology',
 'System/Data Analyst',
 'Fraud Data Analyst',
 'Genomics Scientist (Biologist II)',
 'Sr. Data Scientist, Analytic Marketing',
 'Sr Data Analyst',
 'Data Scientist - Analytics Engineer',
 'Senior Data Architect - Jacksonville Beach Florida',
 'Manager- Data Science',
 'Client Data Analyst',
 'Environmental Scientist/GIS Analyst - Midwest or',
 'Data Scientist, Analytics - Ads Delivery Product',
 'Staff Scientist, Molecular Diagnostics',
 'Data Scientist - Weather Data',
 'Scientist - Ophthalmology',
 'Sr. Data Software Engineer',
 'Scientist II, DMPK',
 'Research Data Scientist',
 'Senior Data Science Manager',
 'ENGINEER - COMPUTER SCIENTIST - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING - SAN ANTONIO OR OKLAHOMA CITY, OKLAHOMA',
 'Data Engineer 2',
 'Medical Lab Scientist, Lab Services - CLC Laboratory (up to 19 hours per week; evenings & weekends)',
 'Data science researcher',
 'Data & Analytics Consultant',
 'Scientist/Associate Scientist, Translational Science',
 'SQL Developer/Data Analyst',
 'Business Data Analyst (Clinical)',
 'Sr. Data Engineer - HBO Max',
 'Senior Principal Data Scientist (Python/R)',
 'IRS Pathways Recent Graduate Program (Social Scientist)',
 'Research Analytics Consultant',
 'Data Scientist (Java)',
 'Data Scientist (Fintech)',
 'Scientist I Metrix',
 'ML-Data Science Engineer with OCR',
 'Senior Scientist, Process Science - Analytical Sciences',
 'Data and Software Engineer',
 'Python Data Engineer',
 'Principal Scientist, HEOR',
 'Project Lead - Advanced Analytics/Data Science',
 'Associate Director, Data Partner, Global Biometrics and Data Science',
 'Data Engineer Enterprise Content Management',
 'Computer Vision / Deep Learning Scientist',
 'Computer Scientist/Computer Engineer/IT Professional',
 'Master Architect - AI/DL Data Scientist',
 '(Clinical Safety Data Scientist), JREVIEW, INFORM',
 'Jr. Data Analyst',
 'Manufacturing Data Analyst Engineer',
 'Senior Applied Data Scientist, Government',
 'Senior Environmental Scientist / Ecologist',
 'Consultant, Advanced Data Analytics & Insights – Digital Analytics',
 'Lead Data Engineer (St. Louis, Austin or Toronto)',
 'Data Analyst - Intex Developer',
 'Data Scientist, Business Information Services',
 'Associate Scientist II / Scientist I',
 'Investigative Data Analyst',
 'Data Scientist, Two Sigma Private Investments',
 'Consultant - Advanced Solutions, Energy Data Scientist - Campus 2021',
 'JPMWM - CARE - Data Scientist - Associate',
 'Public Health Data Scientist',
 'Principal Scientist - Biomarker Specialist',
 'Data Scientist (Financial Transactions)',
 'Big-Data Engineer',
 'GCP Data Architect',
 'Data Engineer ETL Developer',
 'Senior SAS Programmer (Scientist)',
 'Computer Scientist (Public Flyer Notice)',
 'Sr. Machine Learning Engineer',
 'Analytics Manager',
 'Hadoop Data Engineer',
 'Sr. Scientist, Molecular POC',
 'Data Engineer - Trust & Safety, Law Enforcement',
 'Gilbert Data Science Tutor Jobs',
 'Senior Big Data Engineer & Data Scientist (Apps Systems Engineer 6)',
 'Big Data Machine Learning Engineer',
 'Lead Data Scientist - NJ/NY based',
 'Lead Data Engineer',
 'Data Scientist, Game Analytics',
 'Scientist I, Formulation',
 'Data Engineer with Security Clearance',
 'Senior Data Analyst- Guidewire Data Hub',
 'Operations Research Scientist',
 'HR Data Analyst',
 'Financial Data Scientist',
 'Scientist II, QC Life Cycle',
 'Principal Scientist, CAR-T Characterization Lead - Cell Therapies',
 'Data Scientist (Databricks,Spark,PowerBI)',
 'System Performance Modeling Engineer',
 'Senior Scientist-Wind Vulnerability',
 'Data Scientist, SBG',
 'Data Scientist Lead, Capacity Planning & Analytics',
 'Marketing Data Scientist Consultant',
 'Vice President, Director, Data Science',
 'Machine Learning Engineer, R&D',
 'Data Scientist (Demolition Department)',
 'Scientific Data Analyst – Junior',
 'Computational Scientist-Secure Data',
 'Associate Scientist - Organic Chemistry',
 'Chandler Data Science Tutor Jobs',
 'Product Data Scientist',
 'Data Analyst - Clearance Required',
 'Data Scientist RED - DAB',
 'Staff Data Infrastructure Engineer',
 'Scientist - Ocular',
 'Data Scientist, Supply Chain',
 'Associate Director, Data Science',
 'Business Intelligence Analyst Senior',
 'Finance Data Analyst',
 'Data Scientist, Senior',
 'Medical Laboratory Scientist - Full Time - Days',
 'Environmental Scientist Supervisor',
 'Data Engineer I',
 'Manager, Data Science - HBO Max',
 'Field Medical Scientist, LHN/GBM/Breast',
 'Data Scientist, AMP Commerce/ Payments/ Subscription Analytics',
 'CIMD Technology - Data Engineer',
 'Scientist/Sr. Scientist, Oligonucleotide Synthesis',
 'Data Analyst Intern',
 'Data Scientist (Active Secret Clearance)',
 'Data Engineer (AI/ML)',
 'Java with big data engineer',
 'eDiscovery Data Analyst',
 'Food Scientist II - Jackson, MI',
 'Product Development Scientist (Entry Level) (Food science Degree Must)',
 'Summer 2021 Data Engineer Internship',
 'Mid-Level Data Scientist',
 'Clinical Laboratory Scientist - Hematology',
 'Business Intelligence Analyst I, Decision Support Services',
 'Senior Scientist R&D - Nutrition -- Columbus, OH',
 'Data Scientist: Advanced Analytics',
 'Job Role : Data Engineer/Machine learning',
 'Sr Data Engineer-Supply Chain',
 'Research Engineer – Virtual Vehicle Prototypes – Data Analytics',
 'Data Engineer Associate',
 'Senior Staff Data Engineer',
 'Data Scientist II - FRM Analytics & Reporting',
 'Data Scientist - Altdata',
 'Senior Scientist, Immunology',
 'Data Analytics Manager',
 'COMPUTER SCIENTIST - RESEARCH COMPUTER SCIENTIST - SIGNAL PROCESSING',

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4891 entries, 0 to 5887
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Job Title          4891 non-null   object
 1   Salary Estimate    4891 non-null   object
 2   Rating             4891 non-null   float64
 3   Company Name       4891 non-null   object
 4   Location           4891 non-null   object
 5   Size               4891 non-null   object
 6   Founded            4891 non-null   object
 7   Type of ownership  4891 non-null   object
 8   Industry           4891 non-null   object
 9   Sector             4891 non-null   object
 10  Revenue            4891 non-null   object
 11  min_salary         4891 non-null   int64
 12  max_salary         4891 non-null   int64
 13  average_salary     4891 non-null   float64
 14  state              4891 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 611.4+ KB

In [98]:
df.to_csv('df_w5.csv')